---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mydb
  name: mysql
spec:
  containers:
  - image: mysql:5.7
    name: con1
    ports:
    - containerPort: 3306
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: testdb
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mydb

