apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: robo-role
  namespace: devops
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods/exec","pods","deployments" ]
    verbs: [ "get", "list","edit","create","update","delete"  ]

##### role binding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robo-rolebinding
  namespace: devops
subjects:
- kind: ServiceAccount
  name: robo
  namespace: default
roleRef:
  kind: Role
  name: robo-role
  apiGroup: rbac.authorization.k8s.io

