---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress2
  name: wordpress-2
spec:
  containers:
  - image: wordpress:latest
    name: con1
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-svc
    - name: WORDPRESS_DB_NAME
      value: testdb
    - name: WORDPRESS_DB_PASSWORD
      value: test123
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_TABLE_PREFIX
      value: wp2_

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30124
  selector:
    app: wordpress2
  type: NodePort

