apiVersion: v1
kind: ConfigMap
metadata:
  name: myindex
data:
  index.html: |
    <h1>Hello from ConfigMap ....... </h1>

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-cm
  name: nginx-cm
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: myvol
    configMap:
      name: myindex     
---
apiVersion: v1
kind: Service
metadata:
  name: nginxcm-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30123
  selector:
    app: nginx-cm
  type: NodePort

