apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfig
data:
  WORDPRESS_DB_HOST: mysql-svc
  WORDPRESS_DB_NAME: testdb
  WORDPRESS_DB_PASSWORD: test123
  WORDPRESS_DB_USER: root
  WORDPRESS_TABLE_PREFIX: wp_


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  containers:
  - image: wordpress:latest
    name: con1
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
       name: wpconfig
    
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30123
  selector:
    app: wordpress
  type: NodePort

